stages:
  #- npmbuild
  # - maventest
  - autodeploy


#maven-build:
#    stage: mavenbuild
#    tags:
#      - BACKEND
#    only: # Will only run if these conditions are met, check documentation for more!
#      refs:
#        - master
#    script:
#      - cd Backend/cytinerary-backend
#      - mvn package -B

#maven-test:
#    stage: maventest
#    tags:
#      - shell
#    script:
#      - cd Backend/cytinerary-backend
#      - mvn test
#      - mvn package -B
#    artifacts:
#      paths:
#        - Backend/cytinerary-backend/target/*.jar

#npmBuild:
#  stage: npmbuild
#  tags:
#    - FRONTEND
#  only: # Will only run if these conditions are met, check documentation for more!
#    refs:
#      - master
#  script:


autoDeploy:
  stage: autodeploy
  tags:
    - BACKEND
  only: # Will only run if these conditions are met, check documentation for more!
    refs:
      - master
  script:
    - cd Frontend/my-app
    - npm install
    - npm run build
    - npm run test
    - cd ..
    - cd ..
    - sudo rm -r ./Backend/cytinerary-backend/src/main/resources/static/*
    - sudo mv ./Frontend/my-app/build/* ./Backend/cytinerary-backend/src/main/resources/static/
    - cd Backend/cytinerary-backend
    - mvn test
    - mvn package -B
    - sudo mv target/*.war /var/lib/tomcat/cytinerary/cytinerary.war

# android-build:
  #  image: javiersantos/android-ci:latest
  #  stage: androidbuild
  #  before_script:
  #      - export GRADLE_USER_HOME='pwd'/.gradle
  #      - chmod +x ./Frontend/ExercyzeFrontend/gradlew
  #  tags:
  #      - android_tag
  #  script:
  #      - cd Frontend/ExercyzeFrontend/
  #      - ./gradlew assemble
  #  artifacts:
  #      paths:
  #          - Frontend/ExercyzeFrontend/app/build/outputs/

# unitTests:
  #  image: javiersantos/android-ci:latest
  #  stage: androidtest
  #  before_script:
  #      - export GRADLE_USER_HOME='pwd'/.gradle
  #      - chmod +x ./Frontend/ExercyzeFrontend/gradlew
  #  tags:
  #      - android_tag
  #  script:
  #      - cd Frontend/ExercyzeFrontend/
  #      - ./gradlew assemble
